# Generated by Django 5.0 on 2024-02-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bangulorjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewdate', models.DateField()),
                ('companyname', models.CharField(max_length=50)),
                ('tittle', models.CharField(max_length=40)),
                ('qualification', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hydjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewdate', models.DateField()),
                ('companyname', models.CharField(max_length=50)),
                ('tittle', models.CharField(max_length=40)),
                ('qualification', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='punejobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewdate', models.DateField()),
                ('companyname', models.CharField(max_length=50)),
                ('tittle', models.CharField(max_length=40)),
                ('qualification', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.BigIntegerField()),
            ],
        ),
    ]
