# Generated by Django 5.0 on 2024-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangulorjobs',
            name='qualification',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='bangulorjobs',
            name='tittle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='qualification',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='tittle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='qualification',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='tittle',
            field=models.TextField(),
        ),
    ]
