# Generated by Django 5.0 on 2024-02-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_bangulorjobs_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangulorjobs',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='address',
            field=models.TextField(),
        ),
    ]
